name: selectable_autolink_text
description: Generate inline links that can be selected and tapped in text for Flutter.
version: 2.5.0
homepage: https://github.com/miyakeryo/flutter_selectable_autolink_text

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
